server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: *******
    password: *******
    username: *******
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog-master.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
  security:
    user:
      name: *******
      password: *******
      roles: ADMIN, USER, MANAGER
  web:
    resources:
      static-locations[0]: "file:src/main/resources/static/"
      static-locations[1]: "classpath:/static/"

  thymeleaf:
    prefix: classpath:/templates2/bootstrap/
    debug: true
    cache: false
